model_list:
  - model_name: llama3
    litellm_params:
      model: ollama/llama3
      api_base: "http://localhost:11434" # Aponta pro Ollama Host. Com múltiplas réplicas, usaremos o traefik depois ou round robin aqui
  - model_name: mistral
    litellm_params:
      model: ollama/mistral
      api_base: "http://localhost:11434"

router_settings:
  routing_strategy: usage-based-routing-v2 # Load balance inteligente se tiverem multiplos URLs

general_settings:
  master_key: sk-1234 # Chave padrao para os clientes acessarem a AI
